# site settings
title: Kyle Chadwick
subtitle: Portfolio
email: kylepchad@gmail.com
description: Engineer. Medical Augmented Reality. Clinical Biomechanics.
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/kpchad
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/kylepchadwick
pinterest_url:
slack_url:
twitter_url: https://twitter.com/kpchadwick

# build settings
markdown: kramdown

sass:
  style: compressed
